// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ZPG0IuRrC60CdCwfsMdGTQ1IzxCM7Tw',
    appId: '1:775672927669:web:fc39dbbe503e8d23ff35fc',
    messagingSenderId: '775672927669',
    projectId: 'one1quiz',
    authDomain: 'one1quiz.firebaseapp.com',
    storageBucket: 'one1quiz.appspot.com',
    measurementId: 'G-PJ5F90MKG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuCFhlXd5Vk_Cq_INdbfB9Ou2Q_ASxkTc',
    appId: '1:775672927669:android:d6e18d0fc2a745daff35fc',
    messagingSenderId: '775672927669',
    projectId: 'one1quiz',
    storageBucket: 'one1quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH9xrxGZVA18zurwj_Th4r6msEGWXp8e8',
    appId: '1:775672927669:ios:0f8dba9869f3378bff35fc',
    messagingSenderId: '775672927669',
    projectId: 'one1quiz',
    storageBucket: 'one1quiz.appspot.com',
    iosClientId: '775672927669-6mstfgdcvuvu5dg3ljuic8c5pul30dpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH9xrxGZVA18zurwj_Th4r6msEGWXp8e8',
    appId: '1:775672927669:ios:0f8dba9869f3378bff35fc',
    messagingSenderId: '775672927669',
    projectId: 'one1quiz',
    storageBucket: 'one1quiz.appspot.com',
    iosClientId: '775672927669-6mstfgdcvuvu5dg3ljuic8c5pul30dpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
